spring:
  application:
    name: goadviser-eureka-service

server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0